kind: Cluster

apiVersion: kind.x-k8s.io/v1alpha4

networking:
  apiServerAddress: "0.0.0.0"
  apiServerPort: 33893

nodes:

  # ----------------------------------------
  # Control Plane
  # ----------------------------------------
  - role: control-plane

    image: kindest/node:v1.33.1

    extraPortMappings:

      # Frontend NodePort
      - containerPort: 30000
        hostPort: 30000
        protocol: TCP

      # Backend NodePort
      - containerPort: 30001
        hostPort: 30001
        protocol: TCP

  # ----------------------------------------
  # Worker Node
  # ----------------------------------------
  - role: worker

    image: kindest/node:v1.33.1