apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: notes-app
type: Opaque
data:
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4=
  MONGO_INITDB_ROOT_PASSWORD: YWRtaW4xMjM=
  MONGO_INITDB_DATABASE: bm90ZXM=